In [1]:
# ライブラリのインポート
import numpy as np
import pandas as pd
import math

In [2]:
def csv_to_df(file_path, sep = '\t'):
    return pd.read_csv(file_path, sep)

In [3]:
# 単にランキングを出すやつ
import itertools
def get_ranking_matrix(genreChar, test_df):
    file_path = './train/train_{}.tsv'.format(genreChar)
    target_df = csv_to_df(file_path)
    buy_df = target_df[(target_df['event_type'] == 3)&(target_df['ad'] == 1)]
    bl = buy_df['product_id'].value_counts().head(22).index
    ul = test_df[test_df['user_id'].str.contains(genreChar)]['user_id']
    rl = range(0,22)
    result_df = pd.DataFrame(list(itertools.product(ul, bl)))
    result_df[2] = result_df.groupby([0]).cumcount()
    return result_df.as_matrix()

In [143]:
test_file_path = './test/test.tsv'
test_df = csv_to_df(test_file_path)

In [146]:
result_list = []
for c in ['A','B','C','D']:
    result_list.extend(get_ranking_matrix(c, test_df))

In [152]:
pd.DataFrame(result_list).to_csv('ranking.tsv', sep = '\t',header=False,index=False)

In [4]:
file_path = './train/train_{}.tsv'.format('A')
target_df = csv_to_df(file_path)

In [28]:
target_df['ymd'] = pd.to_datetime(target_df['time_stamp']).apply(lambda s: s.strftime('%Y%m%d'))

In [43]:
# 日で区切って、集計できるようにしたい
target_df['time'] = target_df.groupby(['user_id'])['ymd'].rank(method = 'dense', ascending=True)

In [44]:
target_df
# 予定としては、ユーザごとにtimeでピボットした各アクション次元のデータをLSTMに打ち込む
# ターゲットは、広告経由の購入

,user_id,product_id,event_type,ad,time_stamp,time,ymd
0,0000000_A,00009250_a,1,-1,2017-04-08 12:09:04.629,1.0,20170408
1,0000000_A,00009250_a,1,-1,2017-04-27 12:55:57.783,3.0,20170427
2,0000000_A,00014068_a,1,-1,2017-04-08 11:57:53.746,1.0,20170408
3,0000000_A,00001254_a,1,-1,2017-04-08 12:04:26.008,1.0,20170408
4,0000000_A,00003316_a,1,-1,2017-04-08 12:05:31.326,1.0,20170408
5,0000000_A,00003009_a,1,-1,2017-04-14 13:55:07.446,2.0,20170414
6,0000000_A,00004433_a,1,-1,2017-04-27 13:30:18.503,3.0,20170427
7,0000000_A,00004433_a,1,-1,2017-04-27 13:03:18.492,3.0,20170427
8,0000000_A,00008525_a,1,-1,2017-04-27 12:59:09.600,3.0,20170427
9,0000000_A,00009753_a,1,-1,2017-04-27 13:01:27.924,3.0,20170427
10,0000000_A,00009753_a,1,-1,2017-04-27 13:23:55.026,3.0,20170427
11,0000000_A,00013303_a,1,-1,2017-04-27 13:29:54.098,3.0,20170427
12,0000000_A,00003524_a,1,-1,2017-04-27 13:26:46.064,3.0,20170427
13,0000000_A,00012725_a,1,-1,2017-04-27 13:25:28.928,3.0,20170427
14,0000000_A,00008263_a,1,-1,2017-04-27 12:56:42.873,3.0,20170427
15,0000642_A,00009250_a,1,-1,2017-04-05 04:31:04.889,3.0,20170405
16,0000642_A,00003009_a,1,-1,2017-04-05 05:03:28.294,3.0,20170405
17,0000642_A,00010627_a,1,-1,2017-04-09 13:56:18.846,7.0,20170409
18,0000642_A,00009816_a,1,-1,2017-04-06 03:25:29.584,4.0,20170406
19,0000642_A,00009816_a,1,-1,2017-04-06 03:23:25.717,4.0,20170406
20,0000642_A,00012529_a,1,-1,2017-04-06 03:34:42.315,4.0,20170406
21,0000642_A,00012529_a,1,-1,2017-04-14 10:10:52.146,12.0,20170414
22,0000642_A,00003676_a,1,-1,2017-04-05 04:11:16.809,3.0,20170405
23,0000642_A,00001751_a,1,-1,2017-04-05 04:07:16.590,3.0,20170405
24,0000642_A,00001751_a,1,-1,2017-04-06 11:28:58.111,4.0,20170406
25,0000642_A,00000498_a,1,-1,2017-04-08 02:12:18.766,6.0,20170408
26,0000642_A,00013460_a,1,-1,2017-04-06 03:22:17.198,4.0,20170406
27,0000642_A,00011355_a,1,-1,2017-04-05 13:26:46.217,3.0,20170405
28,0000642_A,00008003_a,1,-1,2017-04-06 03:20:20.629,4.0,20170406
29,0000642_A,00002606_a,1,-1,2017-04-06 11:20:11.098,4.0,20170406
...,...,...,...,...,...,...,...
3376463,0058156_A,00003633_a,1,-1,2017-04-28 00:28:28.941,1.0,20170428
3376464,0058156_A,00005612_a,1,-1,2017-04-28 00:34:24.121,1.0,20170428
3376465,0058156_A,00005612_a,1,-1,2017-04-28 00:16:39.018,1.0,20170428
3376466,0058137_A,00010285_a,1,-1,2017-04-27 23:02:04.840,1.0,20170427
3376467,0058137_A,00006644_a,1,-1,2017-04-27 22:57:59.340,1.0,20170427
3376468,0058137_A,00014102_a,1,-1,2017-04-27 22:59:36.943,1.0,20170427
3376469,0058137_A,00009788_a,1,-1,2017-04-27 23:00:12.747,1.0,20170427
3376470,0058137_A,00009788_a,1,-1,2017-04-27 23:00:22.669,1.0,20170427
3376471,0058137_A,00002893_a,1,-1,2017-04-27 23:00:45.916,1.0,20170427
3376472,0058137_A,00013576_a,1,-1,2017-04-27 23:00:33.894,1.0,20170427
3376473,0058137_A,00000721_a,1,-1,2017-04-27 23:01:44.165,1.0,20170427
3376474,0058137_A,00013997_a,1,-1,2017-04-27 23:00:58.158,1.0,20170427
3376475,0058137_A,00011231_a,1,-1,2017-04-27 23:02:32.607,1.0,20170427
3376476,0058137_A,00011221_a,1,-1,2017-04-27 23:03:40.003,1.0,20170427
3376477,0058137_A,00000898_a,1,-1,2017-04-27 22:58:26.287,1.0,20170427
3376478,0058137_A,00002756_a,1,-1,2017-04-27 22:59:28.905,1.0,20170427
3376479,0023567_A,00013216_a,1,-1,2017-04-28 11:02:02.620,1.0,20170428
3376480,0023567_A,00014118_a,1,-1,2017-04-28 10:59:31.265,1.0,20170428
3376481,0023567_A,00011904_a,1,-1,2017-04-28 11:01:07.893,1.0,20170428
3376482,0023567_A,00011904_a,1,-1,2017-04-28 11:07:27.651,1.0,20170428
3376483,0023567_A,00001004_a,1,-1,2017-04-28 11:02:33.940,1.0,20170428
3376484,0023567_A,00010753_a,1,-1,2017-04-28 11:02:38.866,1.0,20170428
3376485,0023567_A,00013809_a,1,-1,2017-04-28 10:58:04.116,1.0,20170428
3376486,0023567_A,00012093_a,1,-1,2017-04-28 11:02:58.514,1.0,20170428
3376487,0023567_A,00005376_a,1,-1,2017-04-28 10:58:48.777,1.0,20170428
3376488,0023567_A,00005376_a,1,-1,2017-04-28 11:07:20.023,1.0,20170428
3376489,0023567_A,00008280_a,1,-1,2017-04-28 11:00:35.549,1.0,20170428
3376490,0023567_A,00001591_a,1,-1,2017-04-28 10:58:51.575,1.0,20170428
3376491,0023567_A,00007688_a,1,-1,2017-04-28 10:59:11.325,1.0,20170428
3376492,0023567_A,00007688_a,1,-1,2017-04-28 11:11:06.644,1.0,20170428