In [1]:
# coding: utf-8

import pandas as pd
import datetime as dt
from sklearn.ensemble import RandomForestRegressor
from sklearn.externals import joblib

In [2]:
train_data = pd.read_csv("../kaggle/train.csv")

In [3]:
import xgboost

In [4]:
train_data[0:20]

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
0,3,1110,7,3301,15766,1212,3,25.14,0,0.0,3
1,3,1110,7,3301,15766,1216,4,33.52,0,0.0,4
2,3,1110,7,3301,15766,1238,4,39.32,0,0.0,4
3,3,1110,7,3301,15766,1240,4,33.52,0,0.0,4
4,3,1110,7,3301,15766,1242,3,22.92,0,0.0,3
5,3,1110,7,3301,15766,1250,5,38.20,0,0.0,5
6,3,1110,7,3301,15766,1309,3,20.28,0,0.0,3
7,3,1110,7,3301,15766,3894,6,56.10,0,0.0,6
8,3,1110,7,3301,15766,4085,4,24.60,0,0.0,4
9,3,1110,7,3301,15766,5310,6,31.68,0,0.0,6
10,3,1110,7,3301,15766,30531,8,62.24,0,0.0,8
11,3,1110,7,3301,15766,30548,4,21.52,0,0.0,4
12,3,1110,7,3301,15766,30571,12,75.00,0,0.0,12
13,3,1110,7,3301,15766,31309,7,43.75,0,0.0,7
14,3,1110,7,3301,15766,31506,10,62.50,0,0.0,10
15,3,1110,7,3301,15766,32393,5,15.10,0,0.0,5
16,3,1110,7,3301,15766,32933,3,21.12,0,0.0,3
17,3,1110,7,3301,15766,32936,3,21.12,0,0.0,3
18,3,1110,7,3301,15766,34053,8,36.00,0,0.0,8
19,3,1110,7,3301,15766,35651,12,90.00,0,0.0,12

In [1]:
import io
import base64
from IPython.display import HTML

#video = io.open('/home/ubuntu/Downloads/test.mp4', 'r+b').read()
encoded = base64.b64encode(video)

HTML(data='''<video alt="test" controls>
     <source src="data:video/mp4;base64,{0}" type="video/mp4" />
     </video>'''.format(encoded.decode('ascii')))

NameError: name 'video' is not defined